server:
  port: 0

spring:
  application:
    name: ride-service

  liquibase:
    change-log: db/changelog/main-changelog.xml

passenger-driver-services:
  wire-mock:
    url: ${MOCK_SERVICE_URI:http://localhost:9090/}