server:
  port: 5003

spring:
  application:
    name: ride-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5435/rides_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}

  jpa:
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        format_sql: true
        ddl-auto: none
    show-sql: true

  liquibase:
    change-log: db/changelog/main-changelog.xml

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

