scrape_configs:
  - job_name: "metrics-discovery-service"
    static_configs:
      - targets: [ "host.docker.internal:8761", "discovery-service:8761" ]
    metrics_path: "/actuator/prometheus"

  - job_name: "metrics-gateway-service"
    static_configs:
      - targets: [ "host.docker.internal:8080", "gateway-service:8080" ]
    metrics_path: "/actuator/prometheus"

  - job_name: "metrics-passenger-service"
    static_configs:
      - targets: [ "host.docker.internal:5002", "passenger-service:5002" ]
    metrics_path: "/actuator/prometheus"

  - job_name: "metrics-driver-service"
    static_configs:
      - targets: [ "host.docker.internal:5001", "driver-service:5001" ]
    metrics_path: "/actuator/prometheus"

  - job_name: "metrics-rides-service"
    static_configs:
      - targets: [ "host.docker.internal:5003", "rides-service:5003" ]
    metrics_path: "/actuator/prometheus"

  - job_name: "metrics-rating-service"
    static_configs:
      - targets: [ "host.docker.internal:5004", "rating-service:5004" ]
    metrics_path: "/actuator/prometheus"