server:
  port: 5004

spring:
  application:
    name: rating-service

  data:
    mongodb:
      uri: ${DB_URI:mongodb://localhost:27017/ratings_db}

  liquibase:
    change-log: db/changelog/main-changelog.xml

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092, localhost:29093, localhost:29094}
      client-id: "average-rating-producer"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}