version: '3.8'

services:
  passengers-db:
    image: postgres:latest
    container_name: passengers_db
    environment:
      POSTGRES_DB: passengers_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - passengers_data:/var/lib/postgresql/data
    networks:
      - cab-aggregator-network
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

networks:
  cab-aggregator-network:
    name: cab-aggregator-network
    driver: bridge

volumes:
  passengers_data: