server:
  port: 8761

spring:
  application:
    name: discovery-service
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092, localhost:29093, localhost:29094}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application:
        - discovery-service
  zipkin:
    tracing:
      endpoint: ${TEMPO_ZIPKIN_URL:http://tempo:9411/api/v2/spans}
  tracing:
    sampling:
      probability: 1.0