server:
  port: 5001

spring:
  application:
    name: driver-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/drivers_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}

  jpa:
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        format_sql: true
        ddl-auto: none
    show-sql: true

  liquibase:
    change-log: db/changelog/main-changelog.xml

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092, localhost:29093, localhost:29094}
      client-id: "driver-average-rating-consumer"
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}